community:
    githubFeeds:
        - https://github.com/ppi/framework/commits/2.1.atom
        - https://github.com/ppi/skeletonapp/commits/2.1.atom
        - https://github.com/ppi/website/commits/master.atom

    twitterUsername: ppi_framework

docs:
    pages:
        - index
        - getting_started
        - application
        - controllers
        - modules
        - routing
        - templating

oauth:
    consumer_key: 8ruiMaLE0DqdPcf06ERnA
    consumer_secret: lPSTTc0s98ZbjP1nLOKYqUfEoXvqxYAVMl28k18SEw
    user_token: 87676072-wIpCK7WTSFIBjlmB8qdt3GLtrvzxLyssOupRuYfo
    user_secret: mNnG03kV1RmGF5Mo58vYrwlYsDyV3JNIBN1erQhoTg