Homepage:
    pattern:  /
    defaults: { _controller: "Application:Index:index"}

Downloads:
    pattern:  /downloads
    defaults: { _controller: "Application:Index:downloads"}

Download:
    pattern:  /download/{fileID}
    defaults: { _controller: "Application:Index:download"}
    requirements:
        _method: POST

About:
    pattern:  /about
    defaults: { _controller: "Application:Index:about"}

Community:
    pattern:  /community
    defaults: { _controller: "Application:Index:community"}

Contributors:
    pattern:  /contributors
    defaults: { _controller: "Application:Index:contributors"}

Projects:
    pattern:  /projects
    defaults: { _controller: "Application:Index:projects"}

NewsletterSubmit:
    pattern:  /newsletter_submit
    defaults: { _controller: "Application:Index:newsletterSubmit"}

DocsIndex:
    pattern:  /docs/{ver}/{page}.html
    defaults: { _controller: "Application:Docs:index", ver: "2.0"}

DocsViewFile:
    pattern:  /docs/view/{ver}/{page}.html
    defaults: { _controller: "Application:Docs:view", ver: "2.0"}

GooglePlus:
    pattern: /gplus
    defaults: { _controller: "Application:Links:gplus"}

Facebook:
    pattern: /facebook
    defaults: { _controller: "Application:Links:facebook"}

Twitter:
    pattern: /twitter
    defaults: { _controller: "Application:Links:twitter"}
