Homepage:
    pattern:  /
    defaults: { _controller: "Application:Index:index"}
    
Download:
    pattern:  /download/{type}
    defaults: { _controller: "Application:Index:download"}

About:
    pattern:  /about
    defaults: { _controller: "Application:Index:about"}

Community:
    pattern:  /community
    defaults: { _controller: "Application:Index:community"}
    
Contributors:
    pattern:  /contributors
    defaults: { _controller: "Application:Index:contributors"}

Chat:
    pattern:  /chat
    defaults: { _controller: "Application:Index:chat"}
    
Projects:
    pattern:  /projects
    defaults: { _controller: "Application:Index:projects"}
    
NewsletterSubmit:
    pattern:  /newsletter_submit
    defaults: { _controller: "Application:Index:newsletterSubmit"}
    
DocsViewFile:
    pattern:  /docs/{page}.html
    defaults: { _controller: "Application:Docs:index"}